all:
  children:
    masters:
      hosts:
        kube0:
          ansible_host: 172.30.0.7
      vars:
        ansible_user: ubuntu

    workers:
      children:
        ubuntu-workers:
          hosts:
            kube1:
              ansible_host: 172.30.0.8
            kube2:
              ansible_host: 172.30.0.9
          vars:
            ansible_user: ubuntu

        raspbian-workers:
          hosts:
            pi0:
              ansible_host: 172.30.0.10
            pi1:
              ansible_host: 172.30.0.11
            pi2:
              ansible_host: 172.30.0.12
          vars:
            ansible_user: pi

  vars:
    ansible_python_interpreter: /usr/bin/python3
