- hosts: raspbian-workers
  become: yes
  tasks:
    - name: update host name
      hostname:
        name: "{{ inventory_hostname }}"

    - name: update /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.1\.1[ \t]+raspberrypi'
        line: "127.0.1.1\t{{ inventory_hostname }}"
        state: present

    - name: disable swap
      shell: dphys-swapfile swapoff && dphys-swapfile uninstall >> swapoff.txt
      args:
        chdir: $HOME
        creates: swapoff.txt

    - name: disable swap on reboot
      systemd:
        name: dphys-swapfile
        enabled: no

    - name: enable cgroup cpuset/memory in boot command
      command: sed -i.bak '1 s|$| cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory|' /boot/cmdline.txt
      args:
        creates: /boot/cmdline.txt.bak
      register:
        bootcmd

    - name: reboot when boot command changed
      reboot:
      when: bootcmd.changed
